-- MySQL Script generated by MySQL Workbench
-- Sun Oct 28 19:52:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`admin` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `mail_2` VARCHAR(100) NULL,
  `local_phone_number` VARCHAR(30) NOT NULL,
  `delocalized_phone_number` VARCHAR(30) NULL,
  `description` MEDIUMTEXT NOT NULL,
  `profession` VARCHAR(100) NULL,
  `avatar` VARCHAR(255) NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`skill` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `rating` SMALLINT(6) NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skill_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_skill_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `portfolio`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`training` (
  `id` INT NOT NULL,
  `training_name` VARCHAR(80) NOT NULL,
  `structure_name` VARCHAR(80) NOT NULL,
  `begin_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_training_admin_idx` (`admin_id` ASC),
  CONSTRAINT `fk_training_admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `portfolio`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `admin` (`id`, `username`, `username_canonical`, `email`, `email_canonical`, `enabled`, `salt`, `password`, `last_login`, `confirmation_token`, `password_requested_at`, `roles`, `first_name`, `last_name`, `birth_date`, `mail`, `mail_2`, `local_phone_number`, `delocalized_phone_number`, `description`, `profession`, `avatar`, `updated_at`) VALUES (NULL, 'sweezy974', 'sweezy974', 'frederic-boyer@live.fr', 'frederic-boyer@live.fr', '1', NULL, '1234', NULL, NULL, NULL, '', 'Frédéric', 'Boyer', '1995-01-17 00:00:00', 'frederic-boyer@live.fr', NULL, '+262 692 789 298', NULL, 'bonjour c\'est fred', NULL, NULL, CURRENT_DATE());
